<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>		
		<TargetFrameworks>net10.0-android;net10.0-ios</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.26100.0</TargetFrameworks>
		<!--<TargetFrameworks>net10.0-android;net10.0-ios;net10.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.19041.0</TargetFrameworks>-->
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net9.0-tizen</TargetFrameworks> -->

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->		
		
		<OutputType>Exe</OutputType>
		<RootNamespace>FileShare.Mobile</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<MauiEnableXamlCBindingWithSourceCompilation>True</MauiEnableXamlCBindingWithSourceCompilation>
		<PublishTrimmed>False</PublishTrimmed>
		<PublishAot>False</PublishAot>
		
		<!-- Display name -->
		<ApplicationTitle>FileShare.Mobile</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.fileshare.mobile</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
		<WindowsPackageType>None</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<!--<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>-->
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<AndroidSigningKeyStore>FileShare.keystore</AndroidSigningKeyStore>
		<!--<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>-->		
	</PropertyGroup>
	<PropertyGroup Condition="'$(TargetFramework)|$(Platform)'=='net10.0-android|AnyCPU'">
		<RuntimeIdentifiers>android-x64;android-x86;android-arm64;android-arm</RuntimeIdentifiers>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-android|AnyCPU'">
	  <AndroidPackageFormat>apk</AndroidPackageFormat>
	  <AndroidEnableMultiDex>False</AndroidEnableMultiDex>
	  <AndroidLinkTool>r8</AndroidLinkTool>
	  <PublishTrimmed>True</PublishTrimmed>
	  <RunAOTCompilation>False</RunAOTCompilation>
	  <EnableLLVM>True</EnableLLVM>
	  <RuntimeIdentifiers>android-arm64;android-arm</RuntimeIdentifiers>
	  <AndroidKeyStore>True</AndroidKeyStore>
	  <AndroidSigningStorePass>123456</AndroidSigningStorePass>
	  <AndroidSigningKeyAlias>FileShare</AndroidSigningKeyAlias>
	  <AndroidSigningKeyPass>123456</AndroidSigningKeyPass>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-android|AnyCPU'">
	  <AndroidEnableMultiDex>False</AndroidEnableMultiDex>
	  <EnableLLVM>True</EnableLLVM>
	  <AndroidKeyStore>True</AndroidKeyStore>
	  <AndroidSigningStorePass>123456</AndroidSigningStorePass>
	  <AndroidSigningKeyAlias>FileShare</AndroidSigningKeyAlias>
	  <AndroidSigningKeyPass>123456</AndroidSigningKeyPass>
	</PropertyGroup>
	
	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#17171a" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#17171a" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />
		
		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<!--<ItemGroup>
	  <Compile Remove="Resources\Fonts\FluentUI.cs" />
	</ItemGroup>

	<ItemGroup>
	  <MauiFont Include="C:\Users\Administrator\.nuget\packages\syncfusion.maui.toolkit\1.0.7\buildTransitive\Resources\Fonts\MauiMaterialAssets.ttf" Link="Resources\Fonts\MauiMaterialAssets.ttf" />
	</ItemGroup>-->

	<ItemGroup>
    <PackageReference Include="CommunityToolkit.Maui" Version="13.0.0" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.2" />
    <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.30" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.2" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.11" />
    <PackageReference Include="Syncfusion.Maui.Toolkit" Version="1.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FileShare.Core\FileShare.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Platforms\Windows\Package.appxmanifest">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>

</Project>
